#!/usr/bin/env tsx

import * as fs from 'fs';
import * as path from 'path';
import {getFallbackPromptCatalog} from '../src/lib/catalog';

const OUTPUT_PATH = path.join(process.cwd(), 'docs', 'supabase-seed-v3-admin.sql');

function escapeSqlString(value: string) {
  return value.replace(/'/g, "''");
}

function sqlString(value: string) {
  return `'${escapeSqlString(value)}'`;
}

function sqlTextArray(values: string[]) {
  const items = values.map((value) => sqlString(value)).join(', ');
  return `array[${items}]::text[]`;
}

function sqlJson(value: unknown) {
  return `${sqlString(JSON.stringify(value))}::jsonb`;
}

function structureValues() {
  const {structures} = getFallbackPromptCatalog('es');
  return structures
    .map(
      (item) => `(
  ${sqlString(item.id)},
  ${sqlJson(item.localizedLabel)},
  ${sqlJson(item.localizedWhatIs)},
  ${sqlJson(item.localizedWhenToUse)},
  ${sqlJson(item.localizedTemplate)},
  ${sqlJson(item.localizedExample)},
  ${sqlTextArray(item.sections)},
  ${sqlTextArray(item.columnOrder)},
  ${item.sortOrder},
  ${item.isActive}
)`
    )
    .join(',\n');
}

function roleValues() {
  const {roles} = getFallbackPromptCatalog('es');
  return roles
    .map(
      (item) => `(
  ${sqlString(item.id)},
  ${sqlJson(item.localizedLabel)},
  ${sqlJson(item.localizedDescription)},
  ${sqlString(item.icon)},
  ${item.sortOrder},
  ${item.isActive}
)`
    )
    .join(',\n');
}

function paletteValues() {
  const {paletteBlocks} = getFallbackPromptCatalog('es');
  return paletteBlocks
    .map(
      (item) => `(
  ${sqlString(item.id)},
  ${sqlJson(item.localizedTitle)},
  ${sqlJson(item.localizedContent)},
  ${sqlString(item.niche)},
  ${sqlString(item.structure)},
  ${sqlString(item.targetColumn)},
  ${sqlString(item.level)},
  ${sqlTextArray(item.tags)},
  ${sqlString(item.image)},
  ${item.sortOrder},
  ${item.isActive}
)`
    )
    .join(',\n');
}

function buildSql() {
  return `-- Generated by scripts/seed-admin-catalog.ts
-- Paste into Supabase SQL Editor after docs/supabase-schema-v3-admin.sql

insert into public.prompt_structures (
  id,
  label,
  what_is,
  when_to_use,
  template,
  example,
  sections,
  column_order,
  sort_order,
  is_active
)
values
${structureValues()}
on conflict (id) do update
set
  label = excluded.label,
  what_is = excluded.what_is,
  when_to_use = excluded.when_to_use,
  template = excluded.template,
  example = excluded.example,
  sections = excluded.sections,
  column_order = excluded.column_order,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;

insert into public.prompt_roles (
  id,
  label,
  description,
  icon,
  sort_order,
  is_active
)
values
${roleValues()}
on conflict (id) do update
set
  label = excluded.label,
  description = excluded.description,
  icon = excluded.icon,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;

insert into public.prompt_palette_blocks (
  id,
  title,
  content,
  niche,
  structure_id,
  target_column,
  level,
  tags,
  image,
  sort_order,
  is_active
)
values
${paletteValues()}
on conflict (id) do update
set
  title = excluded.title,
  content = excluded.content,
  niche = excluded.niche,
  structure_id = excluded.structure_id,
  target_column = excluded.target_column,
  level = excluded.level,
  tags = excluded.tags,
  image = excluded.image,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;
`;
}

function main() {
  const sql = buildSql();
  fs.writeFileSync(OUTPUT_PATH, sql, 'utf8');
  console.log(`Generated ${OUTPUT_PATH}`);
}

main();
